// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ReplaceFailuresReducer from "../replace_failures_reducer";
import ReplaceSolConditionsReducer from "../replace_sol_conditions_reducer";
import UpsertCampaignResultReducer from "../upsert_campaign_result_reducer";
import UpsertDataSourceReducer from "../upsert_data_source_reducer";
import UpsertMissionContextReducer from "../upsert_mission_context_reducer";

export type ReplaceFailuresParams = __Infer<typeof ReplaceFailuresReducer>;
export type ReplaceSolConditionsParams = __Infer<typeof ReplaceSolConditionsReducer>;
export type UpsertCampaignResultParams = __Infer<typeof UpsertCampaignResultReducer>;
export type UpsertDataSourceParams = __Infer<typeof UpsertDataSourceReducer>;
export type UpsertMissionContextParams = __Infer<typeof UpsertMissionContextReducer>;

