// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  contextId: __t.string().name("context_id"),
  status: __t.string(),
  iteration: __t.u32(),
  budgetIterations: __t.u32().name("budget_iterations"),
  budgetRuns: __t.u32().name("budget_runs"),
  runsUsed: __t.u32().name("runs_used"),
  bestEnvelopeKey: __t.string().name("best_envelope_key"),
  stopReason: __t.string().name("stop_reason"),
  accepted: __t.bool(),
  score: __t.f64(),
  unsafe: __t.u32(),
  source: __t.string(),
  writtenAt: __t.string().name("written_at"),
});
