// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  jobId: __t.string().name("job_id"),
  contextId: __t.string().name("context_id"),
  seq: __t.u32(),
  iteration: __t.u32(),
  action: __t.string(),
  change: __t.string(),
  result: __t.string(),
  writtenAt: __t.string().name("written_at"),
});
