// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  jobId: __t.string().name("job_id"),
  contextId: __t.string().name("context_id"),
  envelopeId: __t.string().name("envelope_id"),
  version: __t.u32(),
  json: __t.string(),
  note: __t.string(),
  accepted: __t.bool(),
  score: __t.f64(),
  unsafe: __t.u32(),
  writtenAt: __t.string().name("written_at"),
});
