// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  resultId: __t.string().name("result_id"),
  contextId: __t.string().name("context_id"),
  runIndex: __t.u32().name("run_index"),
  seed: __t.u32(),
  solIndex: __t.u32().name("sol_index"),
  cellX: __t.i32().name("cell_x"),
  cellY: __t.i32().name("cell_y"),
  reason: __t.string(),
  detail: __t.string(),
  side: __t.string(),
});
