// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  imageId: __t.string().name("image_id"),
  sol: __t.u32(),
  camera: __t.string(),
  utcDateTaken: __t.string().name("utc_date_taken"),
  localMeanSolarTime: __t.string().name("local_mean_solar_time"),
  daysAgo: __t.f64().name("days_ago"),
  filePath: __t.string().name("file_path"),
  nasaUrl: __t.string().name("nasa_url"),
  credit: __t.string(),
  isFallback: __t.bool().name("is_fallback"),
  chosenWhy: __t.string().name("chosen_why"),
  lat: __t.option(__t.f64()),
  lon: __t.option(__t.f64()),
  waypointSol: __t.option(__t.u32()).name("waypoint_sol"),
  ingestedAt: __t.string().name("ingested_at"),
});
