// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  imageId: __t.string().name("image_id"),
  analysisJson: __t.string().name("analysis_json"),
  planJson: __t.string().name("plan_json"),
  delayMin: __t.f64().name("delay_min"),
  rangeAu: __t.f64().name("range_au"),
  earthDate: __t.string().name("earth_date"),
  validated: __t.bool(),
  validationReasons: __t.string().name("validation_reasons"),
  compileSource: __t.string().name("compile_source"),
  model: __t.string(),
  writtenAt: __t.string().name("written_at"),
});
