// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  siteId: __t.string().name("site_id"),
  siteLabel: __t.string().name("site_label"),
  startDate: __t.string().name("start_date"),
  sols: __t.u32(),
  terrainKind: __t.string().name("terrain_kind"),
  terrainProductId: __t.option(__t.string()).name("terrain_product_id"),
  terrainNote: __t.option(__t.string()).name("terrain_note"),
  conjunctionThresholdDeg: __t.f64().name("conjunction_threshold_deg"),
  benchmarkAvailable: __t.bool().name("benchmark_available"),
  benchmarkKmPerSol: __t.option(__t.f64()).name("benchmark_km_per_sol"),
  benchmarkNote: __t.option(__t.string()).name("benchmark_note"),
  loadedAt: __t.string().name("loaded_at"),
});
