// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  contextId: __t.string().name("context_id"),
  solIndex: __t.u32().name("sol_index"),
  earthDate: __t.string().name("earth_date"),
  delayMin: __t.f64().name("delay_min"),
  rangeAu: __t.f64().name("range_au"),
  sotDeg: __t.f64().name("sot_deg"),
  comm: __t.string(),
  lsDeg: __t.f64().name("ls_deg"),
  season: __t.string(),
  msd: __t.f64(),
  lmstHours: __t.f64().name("lmst_hours"),
  sunElevationDeg: __t.f64().name("sun_elevation_deg"),
  daylightHours: __t.f64().name("daylight_hours"),
  isDay: __t.bool().name("is_day"),
  dataSource: __t.string().name("data_source"),
});
