// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AgentJob = __t.object("AgentJob", {
  id: __t.string(),
  contextId: __t.string(),
  status: __t.string(),
  iteration: __t.u32(),
  budgetIterations: __t.u32(),
  budgetRuns: __t.u32(),
  runsUsed: __t.u32(),
  bestEnvelopeKey: __t.string(),
  stopReason: __t.string(),
  accepted: __t.bool(),
  score: __t.f64(),
  unsafe: __t.u32(),
  source: __t.string(),
  writtenAt: __t.string(),
});
export type AgentJob = __Infer<typeof AgentJob>;

export const AgentLog = __t.object("AgentLog", {
  id: __t.u64(),
  jobId: __t.string(),
  contextId: __t.string(),
  seq: __t.u32(),
  iteration: __t.u32(),
  action: __t.string(),
  change: __t.string(),
  result: __t.string(),
  writtenAt: __t.string(),
});
export type AgentLog = __Infer<typeof AgentLog>;

export const AgentLogInput = __t.object("AgentLogInput", {
  seq: __t.u32(),
  iteration: __t.u32(),
  action: __t.string(),
  change: __t.string(),
  result: __t.string(),
  writtenAt: __t.string(),
});
export type AgentLogInput = __Infer<typeof AgentLogInput>;

export const CampaignResult = __t.object("CampaignResult", {
  id: __t.string(),
  contextId: __t.string(),
  iteration: __t.u32(),
  side: __t.string(),
  runs: __t.u32(),
  finished: __t.u32(),
  unsafe: __t.u32(),
  blackoutSols: __t.u32(),
  nightSols: __t.u32(),
  operationalSols: __t.u32(),
  meanRoundTrips: __t.f64(),
  meanMissionMin: __t.f64(),
  meanBytesDown: __t.f64(),
  meanEscalations: __t.f64(),
  sols: __t.u32(),
  elapsedMs: __t.f64(),
  seed: __t.u32(),
  writtenAt: __t.string(),
});
export type CampaignResult = __Infer<typeof CampaignResult>;

export const DataSource = __t.object("DataSource", {
  name: __t.string(),
  source: __t.string(),
  version: __t.string(),
  retrieved: __t.option(__t.string()),
  url: __t.option(__t.string()),
  note: __t.option(__t.string()),
});
export type DataSource = __Infer<typeof DataSource>;

export const Envelope = __t.object("Envelope", {
  id: __t.string(),
  jobId: __t.string(),
  contextId: __t.string(),
  envelopeId: __t.string(),
  version: __t.u32(),
  json: __t.string(),
  note: __t.string(),
  accepted: __t.bool(),
  score: __t.f64(),
  unsafe: __t.u32(),
  writtenAt: __t.string(),
});
export type Envelope = __Infer<typeof Envelope>;

export const Failure = __t.object("Failure", {
  id: __t.u64(),
  resultId: __t.string(),
  contextId: __t.string(),
  runIndex: __t.u32(),
  seed: __t.u32(),
  solIndex: __t.u32(),
  cellX: __t.i32(),
  cellY: __t.i32(),
  reason: __t.string(),
  detail: __t.string(),
  side: __t.string(),
});
export type Failure = __Infer<typeof Failure>;

export const FailureInput = __t.object("FailureInput", {
  runIndex: __t.u32(),
  seed: __t.u32(),
  solIndex: __t.u32(),
  cellX: __t.i32(),
  cellY: __t.i32(),
  reason: __t.string(),
  detail: __t.string(),
  side: __t.string(),
});
export type FailureInput = __Infer<typeof FailureInput>;

export const MissionContext = __t.object("MissionContext", {
  id: __t.string(),
  siteId: __t.string(),
  siteLabel: __t.string(),
  startDate: __t.string(),
  sols: __t.u32(),
  terrainKind: __t.string(),
  terrainProductId: __t.option(__t.string()),
  terrainNote: __t.option(__t.string()),
  conjunctionThresholdDeg: __t.f64(),
  benchmarkAvailable: __t.bool(),
  benchmarkKmPerSol: __t.option(__t.f64()),
  benchmarkNote: __t.option(__t.string()),
  loadedAt: __t.string(),
});
export type MissionContext = __Infer<typeof MissionContext>;

export const SolConditionInput = __t.object("SolConditionInput", {
  solIndex: __t.u32(),
  earthDate: __t.string(),
  delayMin: __t.f64(),
  rangeAu: __t.f64(),
  sotDeg: __t.f64(),
  comm: __t.string(),
  lsDeg: __t.f64(),
  season: __t.string(),
  msd: __t.f64(),
  lmstHours: __t.f64(),
  sunElevationDeg: __t.f64(),
  daylightHours: __t.f64(),
  isDay: __t.bool(),
  dataSource: __t.string(),
});
export type SolConditionInput = __Infer<typeof SolConditionInput>;

export const SolConditions = __t.object("SolConditions", {
  id: __t.string(),
  contextId: __t.string(),
  solIndex: __t.u32(),
  earthDate: __t.string(),
  delayMin: __t.f64(),
  rangeAu: __t.f64(),
  sotDeg: __t.f64(),
  comm: __t.string(),
  lsDeg: __t.f64(),
  season: __t.string(),
  msd: __t.f64(),
  lmstHours: __t.f64(),
  sunElevationDeg: __t.f64(),
  daylightHours: __t.f64(),
  isDay: __t.bool(),
  dataSource: __t.string(),
});
export type SolConditions = __Infer<typeof SolConditions>;

