// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  siteId: __t.string(),
  siteLabel: __t.string(),
  startDate: __t.string(),
  sols: __t.u32(),
  terrainKind: __t.string(),
  terrainProductId: __t.option(__t.string()),
  terrainNote: __t.option(__t.string()),
  conjunctionThresholdDeg: __t.f64(),
  benchmarkAvailable: __t.bool(),
  benchmarkKmPerSol: __t.option(__t.f64()),
  benchmarkNote: __t.option(__t.string()),
  loadedAt: __t.string(),
};
