// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  imageId: __t.string(),
  sol: __t.u32(),
  camera: __t.string(),
  utcDateTaken: __t.string(),
  localMeanSolarTime: __t.string(),
  daysAgo: __t.f64(),
  filePath: __t.string(),
  nasaUrl: __t.string(),
  credit: __t.string(),
  isFallback: __t.bool(),
  chosenWhy: __t.string(),
  lat: __t.option(__t.f64()),
  lon: __t.option(__t.f64()),
  waypointSol: __t.option(__t.u32()),
  ingestedAt: __t.string(),
};
