// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  contextId: __t.string(),
  status: __t.string(),
  iteration: __t.u32(),
  budgetIterations: __t.u32(),
  budgetRuns: __t.u32(),
  runsUsed: __t.u32(),
  bestEnvelopeKey: __t.string(),
  stopReason: __t.string(),
  accepted: __t.bool(),
  score: __t.f64(),
  unsafe: __t.u32(),
  source: __t.string(),
  writtenAt: __t.string(),
};
