// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  imageId: __t.string(),
  analysisJson: __t.string(),
  planJson: __t.string(),
  delayMin: __t.f64(),
  rangeAu: __t.f64(),
  earthDate: __t.string(),
  validated: __t.bool(),
  validationReasons: __t.string(),
  compileSource: __t.string(),
  model: __t.string(),
  writtenAt: __t.string(),
};
